## Import dependencies

In [57]:
!pip install bs4 requests dotenv
!pip install lxml --break-system-packages
!pip install pandas
from bs4 import BeautifulSoup
import requests
import os
from dotenv import load_dotenv
import pandas as pd
load_dotenv()

print("Dependencies Imported")

Requirement already satisfied: bs4 in ./.venv/lib/python3.12/site-packages (0.0.2)
Requirement already satisfied: requests in ./.venv/lib/python3.12/site-packages (2.34.2)
Requirement already satisfied: dotenv in ./.venv/lib/python3.12/site-packages (0.9.9)
Requirement already satisfied: beautifulsoup4 in ./.venv/lib/python3.12/site-packages (from bs4) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in ./.venv/lib/python3.12/site-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in ./.venv/lib/python3.12/site-packages (from requests) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in ./.venv/lib/python3.12/site-packages (from requests) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in ./.venv/lib/python3.12/site-packages (from requests) (2026.6.17)
Requirement already satisfied: python-dotenv in ./.venv/lib/python3.12/site-packages (from dotenv) (1.2.2)
Requirement already satisfied: soupsieve>=1.6.1 in ./.venv/lib/python3.12/site-packages (from beautifulsoup4->bs4) (2.8.4)
Requirement already satisfied: typing-extensions>=4.0.0 in ./.venv/lib/python3.12/site-packages (from beautifulsoup4->bs4) (4.15.0)
Requirement already satisfied: lxml in ./.venv/lib/python3.12/site-packages (6.1.1)
Requirement already satisfied: pandas in ./.venv/lib/python3.12/site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in ./.venv/lib/python3.12/site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Dependencies Imported

## Log in to CSES

In [58]:
LOGIN_URL = "https://cses.fi/login"
TARGET_URL = "https://cses.fi/problemset/"
session = requests.Session()

session.headers.update({
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
})

In [59]:
login_page = session.get("https://cses.fi/login")
soup = BeautifulSoup(login_page.text, "lxml")

csrf_token = soup.find("input", {"name": "csrf_token"})["value"]

login_data = {
    "csrf_token": csrf_token,
    "nick": os.getenv("CSES_USERNAME"),
    "pass": os.getenv("CSES_PASSWORD"),
}

In [60]:
login_response = session.post(LOGIN_URL, data=login_data)

In [61]:
print(login_response.url)
check = session.get("https://cses.fi/")
soup_check = BeautifulSoup(check.text, "lxml")
print(soup_check.find("a", href=lambda h: h and "logout" in h))

https://cses.fi/
<a href="/logout" title="Log out"><i aria-label="Log out" class="fas fa-sign-out-alt"></i><span>Log out</span></a>

In [62]:
target_response = session.get(TARGET_URL)

In [63]:
target_response.text

'<!DOCTYPE html>\n<html>\n<head>\n  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width,initial-scale=1">\n  <link rel="stylesheet " type="text/css" href="/cses.css?1" id="styles">\n  <link rel="stylesheet alternate" type="text/css" href="/cses-dark.css?1" id="styles-dark">\n  <meta name="theme-color" content="white" id="theme-color">\n  <script type="application/json" id="darkmode-enabled">false</script>\n  <script src="/ui.js"></script>\n  <link rel="stylesheet" type="text/css" href="/lib/fontawesome/css/all.min.css">\n  <title>CSES - CSES Problem Set - Tasks</title></head>\n<body class="with-sidebar norm-width">\n  <div class="header">\n    <div>\n      <a href="/" class="logo"><img src="/logo.png?1" alt="CSES"></a>\n      <a class="menu-toggle" onclick="document.body.classList.toggle(\'menu-open\');">\n        <i class="fas fa-bars"></i>\n      </a>\n      <div class="controls">\n                <a class="account" href="/user/321052">Esmail</a>\n        <span>&mdash;</span>\n                        <a href="/darkmode" title="Toggle dark mode" onclick="return toggle_theme()"><i aria-label="Dark mode" class="fas fa-adjust"></i><span>Dark mode</span></a>\n                <a href="/logout" title="Log out"><i aria-label="Log out" class="fas fa-sign-out-alt"></i><span>Log out</span></a>\n              </div>\n    </div>\n  </div>\n  <div class="skeleton">\n  <div class="navigation">\n    <div class="title-block">\n                <h1>CSES Problem Set</h1>\n        <ul class="nav">\n<li><a href="/problemset/list">Tasks</a></li>\n<li><a href="/problemset/stats">Statistics</a></li>\n<li><a href="/problemset/hacks">Hacks</a></li>\n</ul>\n    </div>\n    </div>\n\n<div class="content-wrapper">\n<div class="content">\n\n<h2>General</h2><ul class="task-list"><li class="text"><a href="/problemset/text/2433">Introduction</a><li class="link"><a href="https://cses.fi/register/?open">Create new account</a><li class="link"><a href="https://cses.fi/problemset/stats/">Statistics</a></ul><h2>Introductory Problems</h2><ul class="task-list"><li class="task"><a href="/problemset/task/1068">Weird Algorithm</a><span class="detail">170410 / 178106</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1083">Missing Number</a><span class="detail">147213 / 153960</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1069">Repetitions</a><span class="detail">127983 / 132868</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1094">Increasing Array</a><span class="detail">120604 / 124678</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1070">Permutations</a><span class="detail">105797 / 108879</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1071">Number Spiral</a><span class="detail">75000 / 81419</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1072">Two Knights</a><span class="detail">57790 / 59514</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1092">Two Sets</a><span class="detail">62810 / 67278</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1617">Bit Strings</a><span class="detail">71575 / 75392</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1618">Trailing Zeros</a><span class="detail">66372 / 70452</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1754">Coin Piles</a><span class="detail">59003 / 64262</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1755">Palindrome Reorder</a><span class="detail">54817 / 57727</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/2205">Gray Code</a><span class="detail">37332 / 41672</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/2165">Tower of Hanoi</a><span class="detail">34762 / 36093</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1622">Creating Strings</a><span class="detail">46238 / 47373</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1623">Apple Division</a><span class="detail">46826 / 52593</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1624">Chessboard and Queens</a><span class="detail">28497 / 28978</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/3399">Raab Game I</a><span class="detail">6892 / 7773</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/3419">Mex Grid Construction</a><span class="detail">6712 / 7044</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/3217">Knight Moves Grid</a><span class="detail">6771 / 6921</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/3311">Grid Coloring I</a><span class="detail">5691 / 5892</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/2431">Digit Queries</a><span class="detail">20047 / 23046</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1743">String Reorder</a><span class="detail">5120 / 5871</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1625">Grid Path Description</a><span class="detail">11209 / 14395</span> <span class="task-score icon zero"></span></ul><h2>Sorting and Searching</h2><ul class="task-list"><li class="task"><a href="/problemset/task/1621">Distinct Numbers</a><span class="detail">84555 / 91068</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1084">Apartments</a><span class="detail">63429 / 69899</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1090">Ferris Wheel</a><span class="detail">60962 / 65390</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1091">Concert Tickets</a><span class="detail">48955 / 56574</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1619">Restaurant Customers</a><span class="detail">49772 / 53510</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1629">Movie Festival</a><span class="detail">48298 / 50985</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1640">Sum of Two Values</a><span class="detail">56042 / 62354</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1643">Maximum Subarray Sum</a><span class="detail">53624 / 55874</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1074">Stick Lengths</a><span class="detail">48044 / 50124</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/2183">Missing Coin Sum</a><span class="detail">36626 / 37899</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/2216">Collecting Numbers</a><span class="detail">37494 / 39980</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/2217">Collecting Numbers II</a><span class="detail">16306 / 20424</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1141">Playlist</a><span class="detail">37475 / 42526</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1073">Towers</a><span class="detail">37525 / 40061</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1163">Traffic Lights</a><span class="detail">29158 / 32460</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/3420">Distinct Values Subarrays</a><span class="detail">9255 / 10470</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/3421">Distinct Values Subsequences</a><span class="detail">7106 / 7780</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/2162">Josephus Problem I</a><span class="detail">22571 / 24706</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/2163">Josephus Problem II</a><span class="detail">12322 / 16877</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/2168">Nested Ranges Check</a><span class="detail">13397 / 15207</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/2169">Nested Ranges Count</a><span class="detail">8993 / 10539</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1164">Room Allocation</a><span class="detail">22020 / 25108</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1620">Factory Machines</a><span class="detail">31815 / 34434</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1630">Tasks and Deadlines</a><span class="detail">25444 / 25945</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1631">Reading Books</a><span class="detail">20616 / 22014</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1641">Sum of Three Values</a><span class="detail">29952 / 32972</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1642">Sum of Four Values</a><span class="detail">18685 / 20649</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1645">Nearest Smaller Values</a><span class="detail">25021 / 25839</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1660">Subarray Sums I</a><span class="detail">33160 / 35221</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1661">Subarray Sums II</a><span class="detail">30222 / 35504</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1662">Subarray Divisibility</a><span class="detail">27353 / 29629</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/2428">Distinct Values Subarrays II</a><span class="detail">16680 / 18176</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1085">Array Division</a><span class="detail">25890 / 27165</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1632">Movie Festival II</a><span class="detail">14020 / 16759</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1644">Maximum Subarray Sum II</a><span class="detail">13043 / 15422</span> <span class="task-score icon full"></span></ul><h2>Dynamic Programming</h2><ul class="task-list"><li class="task"><a href="/problemset/task/1633">Dice Combinations</a><span class="detail">88434 / 93367</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1634">Minimizing Coins</a><span class="detail">76522 / 81941</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1635">Coin Combinations I</a><span class="detail">69950 / 75443</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1636">Coin Combinations II</a><span class="detail">59245 / 66653</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1637">Removing Digits</a><span class="detail">65823 / 67113</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1638">Grid Paths I</a><span class="detail">61932 / 63603</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1158">Book Shop</a><span class="detail">55725 / 60978</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1746">Array Description</a><span class="detail">41174 / 45473</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/2413">Counting Towers</a><span class="detail">25448 / 26902</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1639">Edit Distance</a><span class="detail">41151 / 43323</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/3403">Longest Common Subsequence</a><span class="detail">13226 / 13688</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1744">Rectangle Cutting</a><span class="detail">33958 / 36946</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/3359">Minimal Grid Path</a><span class="detail">6013 / 10217</span> <span class="task-score icon zero"></span><li class="task"><a href="/problemset/task/1745">Money Sums</a><span class="detail">40110 / 41554</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1097">Removal Game</a><span class="detail">24533 / 31979</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1093">Two Sets II</a><span class="detail">31545 / 33804</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/3314">Mountain Range</a><span class="detail">4180 / 7272</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1145">Increasing Subsequence</a><span class="detail">32164 / 35980</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1140">Projects</a><span class="detail">22464 / 24954</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1653">Elevator Rides</a><span class="detail">14577 / 18134</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/2181">Counting Tilings</a><span class="detail">8568 / 9278</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/2220">Counting Numbers</a><span class="detail">12669 / 14081</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1748">Increasing Subsequence II</a><span class="detail">5597 / 6523</span> <span class="task-score icon full"></span></ul><h2>Graph Algorithms</h2><ul class="task-list"><li class="task"><a href="/problemset/task/1192">Counting Rooms</a><span class="detail">61244 / 64173</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1193">Labyrinth</a><span class="detail">43241 / 51083</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1666">Building Roads</a><span class="detail">53623 / 55457</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1667">Message Route</a><span class="detail">46372 / 48102</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1668">Building Teams</a><span class="detail">43796 / 46001</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1669">Round Trip</a><span class="detail">34655 / 37553</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1194">Monsters</a><span class="detail">24354 / 28289</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1671">Shortest Routes I</a><span class="detail">38213 / 41807</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1672">Shortest Routes II</a><span class="detail">30933 / 34452</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1673">High Score</a><span class="detail">19572 / 26714</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1195">Flight Discount</a><span class="detail">25080 / 28974</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1197">Cycle Finding</a><span class="detail">17704 / 21337</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1196">Flight Routes</a><span class="detail">17260 / 19114</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1678">Round Trip II</a><span class="detail">19263 / 21473</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1679">Course Schedule</a><span class="detail">25578 / 26885</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1680">Longest Flight Route</a><span class="detail">18537 / 22491</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1681">Game Routes</a><span class="detail">20313 / 21613</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1202">Investigation</a><span class="detail">15238 / 16294</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1750">Planets Queries I</a><span class="detail">13211 / 15318</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1160">Planets Queries II</a><span class="detail">4850 / 6059</span> <span class="task-score icon zero"></span><li class="task"><a href="/problemset/task/1751">Planets Cycles</a><span class="detail">8083 / 8957</span> <span class="task-score icon "></span><li class="task"><a href="/problemset/task/1675">Road Reparation</a><span class="detail">19871 / 20665</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1676">Road Construction</a><span class="detail">21728 / 22398</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1682">Flight Routes Check</a><span class="detail">17250 / 18597</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1683">Planets and Kingdoms</a><span class="detail">14008 / 14612</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1684">Giant Pizza</a><span class="detail">5925 / 6472</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1686">Coin Collector</a><span class="detail">9266 / 10168</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1691">Mail Delivery</a><span class="detail">7451 / 8109</span> <span class="task-score icon "></span><li class="task"><a href="/problemset/task/1692">De Bruijn Sequence</a><span class="detail">3956 / 4136</span> <span class="task-score icon "></span><li class="task"><a href="/problemset/task/1693">Teleporters Path</a><span class="detail">5757 / 6506</span> <span class="task-score icon "></span><li class="task"><a href="/problemset/task/1690">Hamiltonian Flights</a><span class="detail">8735 / 9892</span> <span class="task-score icon full"></span><li class="task"><a href="/problemset/task/1689">Knight\'s Tour</a><span class="detail">3319 / 3980</span> <span class="task-score icon "></span><li class="task"><a href="/problemset/task/1694">Download Speed</a><span class="detail">5767 / 7557</span> <span class="task-score icon "></span><li class="task"><a href="/problemset/task/1695">Police Chase</a><span class="detail">4576 / 5093</span> <span class="task-score icon "></span><li class="task"><a href="/problemset/task/1696">School Dance</a><span class="detail">5026 / 5301</span> <span class="task-score

In [64]:
soup = BeautifulSoup(target_response.text, 'lxml')

In [65]:
headers = soup.select('h2')
headers.pop(0)
print(headers)

[<h2>Introductory Problems</h2>, <h2>Sorting and Searching</h2>, <h2>Dynamic Programming</h2>, <h2>Graph Algorithms</h2>, <h2>Range Queries</h2>, <h2>Tree Algorithms</h2>, <h2>Mathematics</h2>, <h2>String Algorithms</h2>, <h2>Geometry</h2>, <h2>Advanced Techniques</h2>, <h2>Sliding Window Problems</h2>, <h2>Interactive Problems</h2>, <h2>Bitwise Operations</h2>, <h2>Construction Problems</h2>, <h2>Advanced Graph Problems</h2>, <h2>Counting Problems</h2>, <h2>Additional Problems I</h2>, <h2>Additional Problems II</h2>]

## Parse HTML into a dictionary + dataframe

In [66]:
# Segment name: [(Problem name, Solved by me, total solved, total attempts)]
ans = {}

df = pd.DataFrame({
    'Header': [],
    'Problem Name': [],
    'Solved By Me': [],
    'Solve Count' : [],
    'Attempt Count': [] 
})


for header in headers:
    n = header.text

    ans[n] = []
    task_list = header.next_sibling.select('li')
    tasks = task_list
    for task in tasks:
        done = True if len(task.select('span.full')) >= 1 else False
        task_name = task.select_one('a').text
        
        solve_count_numbers = task.select_one('span.detail').text

        solve_count_numbers = solve_count_numbers.split('/')

        attempts = solve_count_numbers[-1].strip()
        solve_count = solve_count_numbers[0].strip()

        solve_count, attempts = int(solve_count), int(attempts)

        row = (task_name, done, solve_count, attempts)

        ans[n].append(row)

        row = pd.DataFrame({
            'Header': [n],
            'Problem Name': [row[0]],
            'Solved By Me': [row[1]],
            'Solve Count' : [row[2]],
            'Attempt Count': [row[3]]
        })

        df = pd.concat([df, row], ignore_index=True)

df['Header'] = df['Header'].astype(str)
df['Problem Name'] = df['Problem Name'].astype(str)
df['Solved By Me'] = df['Solved By Me'].astype(bool)
df['Solve Count'] = df['Solve Count'].astype(int)
df['Attempt Count'] = df['Attempt Count'].astype(int)

ans

{'Introductory Problems': [('Weird Algorithm', True, 170410, 178106),
  ('Missing Number', True, 147213, 153960),
  ('Repetitions', True, 127983, 132868),
  ('Increasing Array', True, 120604, 124678),
  ('Permutations', True, 105797, 108879),
  ('Number Spiral', True, 75000, 81419),
  ('Two Knights', True, 57790, 59514),
  ('Two Sets', True, 62810, 67278),
  ('Bit Strings', True, 71575, 75392),
  ('Trailing Zeros', True, 66372, 70452),
  ('Coin Piles', True, 59003, 64262),
  ('Palindrome Reorder', True, 54817, 57727),
  ('Gray Code', True, 37332, 41672),
  ('Tower of Hanoi', True, 34762, 36093),
  ('Creating Strings', True, 46238, 47373),
  ('Apple Division', True, 46826, 52593),
  ('Chessboard and Queens', True, 28497, 28978),
  ('Raab Game I', True, 6892, 7773),
  ('Mex Grid Construction', True, 6712, 7044),
  ('Knight Moves Grid', True, 6771, 6921),
  ('Grid Coloring I', True, 5691, 5892),
  ('Digit Queries', True, 20047, 23046),
  ('String Reorder', True, 5120, 5871),
  ('Grid Path Description', False, 11209, 14395)],
 'Sorting and Searching': [('Distinct Numbers', True, 84555, 91068),
  ('Apartments', True, 63429, 69899),
  ('Ferris Wheel', True, 60962, 65390),
  ('Concert Tickets', True, 48955, 56574),
  ('Restaurant Customers', True, 49772, 53510),
  ('Movie Festival', True, 48298, 50985),
  ('Sum of Two Values', True, 56042, 62354),
  ('Maximum Subarray Sum', True, 53624, 55874),
  ('Stick Lengths', True, 48044, 50124),
  ('Missing Coin Sum', True, 36626, 37899),
  ('Collecting Numbers', True, 37494, 39980),
  ('Collecting Numbers II', True, 16306, 20424),
  ('Playlist', True, 37475, 42526),
  ('Towers', True, 37525, 40061),
  ('Traffic Lights', True, 29158, 32460),
  ('Distinct Values Subarrays', True, 9255, 10470),
  ('Distinct Values Subsequences', True, 7106, 7780),
  ('Josephus Problem I', True, 22571, 24706),
  ('Josephus Problem II', True, 12322, 16877),
  ('Nested Ranges Check', True, 13397, 15207),
  ('Nested Ranges Count', True, 8993, 10539),
  ('Room Allocation', True, 22020, 25108),
  ('Factory Machines', True, 31815, 34434),
  ('Tasks and Deadlines', True, 25444, 25945),
  ('Reading Books', True, 20616, 22014),
  ('Sum of Three Values', True, 29952, 32972),
  ('Sum of Four Values', True, 18685, 20649),
  ('Nearest Smaller Values', True, 25021, 25839),
  ('Subarray Sums I', True, 33160, 35221),
  ('Subarray Sums II', True, 30222, 35504),
  ('Subarray Divisibility', True, 27353, 29629),
  ('Distinct Values Subarrays II', True, 16680, 18176),
  ('Array Division', True, 25890, 27165),
  ('Movie Festival II', True, 14020, 16759),
  ('Maximum Subarray Sum II', True, 13043, 15422)],
 'Dynamic Programming': [('Dice Combinations', True, 88434, 93367),
  ('Minimizing Coins', True, 76522, 81941),
  ('Coin Combinations I', True, 69950, 75443),
  ('Coin Combinations II', True, 59245, 66653),
  ('Removing Digits', True, 65823, 67113),
  ('Grid Paths I', True, 61932, 63603),
  ('Book Shop', True, 55725, 60978),
  ('Array Description', True, 41174, 45473),
  ('Counting Towers', True, 25448, 26902),
  ('Edit Distance', True, 41151, 43323),
  ('Longest Common Subsequence', True, 13226, 13688),
  ('Rectangle Cutting', True, 33958, 36946),
  ('Minimal Grid Path', False, 6013, 10217),
  ('Money Sums', True, 40110, 41554),
  ('Removal Game', True, 24533, 31979),
  ('Two Sets II', True, 31545, 33804),
  ('Mountain Range', True, 4180, 7272),
  ('Increasing Subsequence', True, 32164, 35980),
  ('Projects', True, 22464, 24954),
  ('Elevator Rides', True, 14577, 18134),
  ('Counting Tilings', True, 8568, 9278),
  ('Counting Numbers', True, 12669, 14081),
  ('Increasing Subsequence II', True, 5597, 6523)],
 'Graph Algorithms': [('Counting Rooms', True, 61244, 64173),
  ('Labyrinth', True, 43241, 51083),
  ('Building Roads', True, 53623, 55457),
  ('Message Route', True, 46372, 48102),
  ('Building Teams', True, 43796, 46001),
  ('Round Trip', True, 34655, 37553),
  ('Monsters', True, 24354, 28289),
  ('Shortest Routes I', True, 38213, 41807),
  ('Shortest Routes II', True, 30933, 34452),
  ('High Score', True, 19572, 26714),
  ('Flight Discount', True, 25080, 28974),
  ('Cycle Finding', True, 17704, 21337),
  ('Flight Routes', True, 17260, 19114),
  ('Round Trip II', True, 19263, 21473),
  ('Course Schedule', True, 25578, 26885),
  ('Longest Flight Route', True, 18537, 22491),
  ('Game Routes', True, 20313, 21613),
  ('Investigation', True, 15238, 16294),
  ('Planets Queries I', True, 13211, 15318),
  ('Planets Queries II', False, 4850, 6059),
  ('Planets Cycles', False, 8083, 8957),
  ('Road Reparation', True, 19871, 20665),
  ('Road Construction', True, 21728, 22398),
  ('Flight Routes Check', True, 17250, 18597),
  ('Planets and Kingdoms', True, 14008, 14612),
  ('Giant Pizza', True, 5925, 6472),
  ('Coin Collector', True, 9266, 10168),
  ('Mail Delivery', False, 7451, 8109),
  ('De Bruijn Sequence', False, 3956, 4136),
  ('Teleporters Path', False, 5757, 6506),
  ('Hamiltonian Flights', True, 8735, 9892),
  ("Knight's Tour", False, 3319, 3980),
  ('Download Speed', False, 5767, 7557),
  ('Police Chase', False, 4576, 5093),
  ('School Dance', False, 5026, 5301),
  ('Distinct Routes', False, 3568, 4598)],
 'Range Queries': [('Static Range Sum Queries', True, 42812, 44698),
  ('Static Range Minimum Queries', True, 29549, 31608),
  ('Dynamic Range Sum Queries', True, 30706, 32032),
  ('Dynamic Range Minimum Queries', True, 27789, 28447),
  ('Range Xor Queries', True, 28536, 28913),
  ('Range Update Queries', True, 22905, 24487),
  ('Forest Queries', True, 23550, 24373),
  ('Hotel Queries', True, 16671, 17620),
  ('List Removals', True, 13837, 14505),
  ('Salary Queries', True, 10608, 13182),
  ('Prefix Sum Queries', True, 8945, 9624),
  ('Pizzeria Queries', True, 7189, 7441),
  ('Visible Buildings Queries', True, 2059, 2238),
  ('Range Interval Queries', False, 1575, 2110),
  ('Subarray Sum Queries', True, 8304, 8971),
  ('Subarray Sum Queries II', False, 2306, 2379),
  ('Distinct Values Queries', True, 7860, 9553),
  ('Distinct Values Queries II', False, 1303, 1483),
  ('Increasing Array Queries', False, 3004, 3425),
  ('Movie Festival Queries', False, 1649, 1816),
  ('Forest Queries II', False, 4934, 5285),
  ('Range Updates and Sums', False, 6853, 8044),
  ('Polynomial Queries', False, 5055, 5919),
  ('Range Queries and Copies', False, 3586, 3823),
  ('Missing Coin Sum Queries', False, 815, 1132)],
 'Tree Algorithms': [('Subordinates', True, 35180, 37587),
  ('Tree Matching', True, 20198, 23301),
  ('Tree Diameter', True, 28701, 30335),
  ('Tree Distances I', False, 22181, 23757),
  ('Tree Distances II', False, 18088, 18898),
  ('Company Queries I', True, 20251, 21270),
  ('Company Queries II', True, 18925, 19886),
  ('Distance Queries', True, 17129, 18318),
  ('Counting Paths', False, 10804, 11411),
  ('Subtree Queries', True, 12794, 13594),
  ('Path Queries', True, 10318, 10890),
  ('Path Queries II', False, 4341, 6390),
  ('Distinct Colors', False, 9926, 10872),
  ('Finding a Centroid', False, 8048, 8372),
  ('Fixed-Length Paths I', False, 4003, 5047),
  ('Fixed-Length Paths II', False, 1931, 3401)],
 'Mathematics': [('Josephus Queries', True, 5585, 6988),
  ('Exponentiation', True, 27574, 29359),
  ('Exponentiation II', True, 19262, 22900),
  ('Counting Divisors', True, 25159, 28304),
  ('Common Divisors', True, 16249, 18763),
  ('Sum of Divisors', True, 9210, 13562),
  ('Divisor Analysis', True, 6338, 8401),
  ('Prime Multiples', True, 7338, 8498),
  ('Counting Coprime Pairs', True, 4863, 5613),
  ('Next Prime', False, 2455, 2804),
  ('Binomial Coefficients', False, 11797, 13035),
  ('Creating Strings II', True, 9769, 10285),
  ('Distributing Apples', True, 9300, 9977),
  ('Christmas Party', False, 7745, 8266),
  ('Permutation Order', False, 1180, 1214),
  ('Permutation Rounds', True, 1692, 1877),
  ('Bracket Sequences I', False, 5176, 5621),
  ('Bracket Sequences II', False, 2740, 3125),
  ('Counting Necklaces', False, 2514, 2717),
  ('Counting Grids', False, 2102, 2232),
  ('Fibonacci Numbers', False, 7786, 9698),
  ('Throwing Dice', False, 4102, 4445),
  ('Graph Paths I', False, 3971, 4235),
  ('Graph Paths II', False, 3322, 3478),
  ('System of Linear Equations', False, 589, 641),
  ('Sum of Four Squares', False, 871, 1013),
  ('Triangle Number Sums', False, 735, 886),
  ('Dice Probability', False, 3477, 3736),
  ('Moving Robots', False, 1807, 1906),
  ('Candy Lottery', False, 1813, 3448),
  ('Inversion Probability', False, 531, 2566),
  ('Stick Game', False, 3983, 4076),
  ('Nim Game I', False, 5309, 5501),
  ('Nim Game II', False, 4196, 4362),
  ('Stair Game', False, 2851, 3092),
  ("Grundy's Game", False, 1987, 2600),
  ('Another Game', False, 2253, 2424)],
 'String Algorithms': [('Word Combinations', True, 6840, 9720),
  ('String Matching', True, 13101, 17329),
  ('Finding Borders', True, 9647, 10503),
  ('Finding Periods', False, 6875, 7759),
  ('Minimal Rotation', False, 3400, 5012),
  ('Longest Palindrome', False, 5043, 6566),
  ('All Palindromes', False, 847, 949),
  ('Required Substring', False, 1937, 2880),
  ('Palindrome Queries', False, 2377, 2747),
  ('Finding Patterns', False, 2237, 3100),
  ('Counting Patterns', False, 2123, 2596),
  ('Pattern Positions', False, 1787, 2152),
  ('Distinct Substrings', False, 2010, 2379),
  ('Distinct Subsequences', False, 1283, 1360),
  ('Repeating Substring', False, 2178, 2503),
  ('String Functions', False, 1912, 2006),
  ('Inverse Suffix Array', False, 339, 389),
  ('String Transform', False, 650, 775),
  ('Substring Order I', False, 1382, 1528),
  ('Substring Order II', False, 925, 1192),
  ('Substring Distribution', False, 1278, 1382)],
 'Geometry': [('Point Location Test', False, 8294, 9213),
  ('Line Segment Intersection', False, 4921, 6129),
  ('Polygon Area', False, 5662, 5976),
  ('Point in Polygon', False, 3154, 3979),
  ('Polygon Lattice Points', False, 2558, 2743),
  ('Minimum Euclidean Distance', False, 2264, 3179),
  ('Convex Hull', False, 3783, 4495),
  ('Maximum Manhattan Distances', False, 758, 787),
  ('All Manhattan Distances', False, 772, 850),
  ('Intersection Points', False, 2232, 2406),
  ('Line Segments Trace I', False, 425, 439),
  ('Line Segments Trace II', False, 351, 371),
  ('Lines and Queries I', False, 466, 489),
  ('Lines and Queries II', False, 413, 434),
  ('Area of Rectangles', False, 1298, 1448),
  ('Robot Path', False, 353, 652)],
 'Advanced Techniques': [('Meet in the Middle', True, 7555, 10307),
  ('Hamming Distance', False, 3532, 3861),
  ('Corner Subgrid Check', False, 259, 626),
  ('Corner Subgrid Count', False, 2431, 2748),
  ('Reachable Nodes', False, 2515, 2701),
  ('Reachability Queries', False, 1684, 1974),
  ('Cut and Paste', False, 1719, 1899),
  ('Substring Reversals', False, 1512, 1639),
  ('Reversals and Sums', False, 1537, 1645),
  ('Necessary Roads', False, 2217, 2275),
  ('Necessary Cities', False, 2062, 2155),
  ('Eulerian Subgraphs', False, 886, 933),
  ('Monster Game I', False, 1320, 1464),
  ('Monster Game II', False, 1167, 1246),
  ('Subarray Squares', False, 1657, 1926),
  ('Houses and Schools', False, 902, 1067),
  ('Knuth Division', False, 1077, 1210),
  ('Apples and Bananas', False, 1232, 1335),
  ('One Bit Positions', False, 947, 1030),
  ('Signal Processing', False, 922, 986),
  ('New Roads Queries', True, 2507, 3021),
  ('Dynamic Connectivity', False, 1152, 1292),
  ('Parcel Delivery', False, 894, 981),
  ('Task Assignment', False, 1028, 1108),
  ('Distinct Routes II', False, 679, 769)],
 'Sliding Window Problems': [('Sliding Window Sum', True, 7137, 7375),
  ('Sliding Window Minimum', True, 5336, 6081),
  ('Sliding Window Xor', True, 5265, 5338),
  ('Sliding Window Or', True, 2362, 3937),
  ('Sliding Window Distinct Values', True, 3674, 4354),
  ('Sliding Window Mode', True, 2917, 3089),
  ('Sliding Window Mex', True, 2744, 2890),
  ('Sliding Window Median', True, 14843, 16888),
  ('Sliding Window Cost', True, 9708, 11164),
  ('Sliding Window Inversions', False, 1490, 1578),
  ('Sliding Window Advertisement', False, 292, 462)],
 'Interactive Problems': [('Hidden Integer', False, 2681, 2794),
  ('Hidden Permutation', False, 1185, 1375),
  ('K-th Highest Score', False, 530, 640),
  ('Permuted Binary Strings', False, 636, 653),
  ('Colored Chairs', False, 593, 629),
  ('Inversion Sorting', False, 343, 384)],
 'Bitwise Operations': [('Counting Bits', True, 5828, 7499),
  ('Maximum Xor Subarray', False, 3467, 3962),
  ('Maximum Xor Subset', False, 1225, 1342),
  ('Number of Subset Xors', False, 1073, 1095),
  ('K Subset Xors', False, 557, 655),
  ('All Subarray Xors', False, 333, 528),
  ('Xor Pyramid Peak', False, 2307, 2780),
  ('Xor Pyramid Diagonal', False, 378, 423),
  ('Xor Pyramid Row', False, 327, 382),
  ('SOS Bit Problem', False, 2427, 2572),
  ('And Subset Count', False, 529, 551)],
 'Construction Problems': [('Inverse Inversions', False, 1935, 2066),
  ('Monotone Subsequences', False, 1170, 1386),
  ('Third Permutation', False, 492, 609),
  ('Permutation Prime Sums', False, 504, 543),
  ('Chess Tournament', False, 1333, 1539),
  ('Distinct Sums Grid', False, 177, 261),
  ('Filling Trominos', False, 289, 496),
  ('Grid Path Construction', False, 154, 478)],
 'Advanced Graph Problems': [('Nearest Shops', False, 841, 1086),
  ('Prüfer Code', False, 1657, 1780),
  ('Tree Traversals', False, 1354, 1486),
  ('Course Schedule II', False, 2190, 3091),
  ('Acyclic Graph Edges', False, 2381, 2519),
  ('Strongly Connected Edges', False, 1693, 1978),
  ('Even Outdegree Edges', False, 1501, 1745),
  ('Graph Girth', False, 3790, 4284),
  ('Fixed Length Walk Queries', False, 421, 467),
  ('Transfer Speeds Sum', False, 485, 500),
  ('MST Edge Check', True, 774, 841),
  ('MST Edge Set Check', False, 293, 329),
  ('MST Edge Cost', False, 463, 485),
  ('Network Breakdown', False, 1283, 1396),
  ('Tree Coin Collecting I', False, 420, 454),
  ('Tree Coin Collecting II', False, 236, 270),
  ('Tree Isomorphism I', False, 1186, 1403),
  ('Tree Isomorphism II', False, 977, 1122),
  ('Flight Route Requests', False, 553, 682),
  ('Critical Cities', False, 475, 718),
  ('Visiting Cities', False, 738, 969),
  ('Graph Coloring', False, 268, 313),
  ('Bus Companies', False, 311, 322),
  ('Split into Two Paths', False, 123, 214),
  ('Network Renovation', False, 1006, 1325),
  ('Forbidden Cities', False, 926, 1206),
  ('Creating Offices', False, 456, 594),
  ('New Flight Routes', True, 375, 980)],
 'Counting Problems': [('Filled Subgrid Count I', False, 696, 780),
  ('Filled Subgrid Count II', False, 377, 465),
  ('All Letter Subgrid Count I', False, 214, 311),
  ('All Letter Subgrid Count II', False, 160, 206),
  ('Border Subgrid Count I', False, 113, 197),
  ('Border Subgrid Count II', False, 124, 144),
  ('Raab Game II', False, 128, 147),
  ('Empty String', False, 1840, 2229),
  ('Permutation Inversions', False, 1101, 1216),
  ('Counting Bishops', False, 431, 479),
  ('Counting Sequences', False, 737, 793),
  ('Grid Paths II', False, 827, 1036),
  ('Counting Permutations', False, 960, 1083),
  ('Grid Completion', False, 245, 310),
  ('Counting Reorders', False, 282, 395),
  ('Tournament Graph Distribution', False, 128, 138),
  ('Collecting Numbers Distribution', False, 136, 143),
  ('Functional Graph Distribution', False, 266, 326)],
 'Additional Problems I': [('Shortest Subsequence', False, 3190, 4183),
  ('Distinct Values Sum', False, 788, 812),
  ('Distinct Values Splits', False, 557, 596),
  ('Swap Game', False, 2186, 2801),
  ('Beautiful Permutation II', False, 671, 1021),
  ('Multiplication Table', True, 7474, 8312),
  ('Bubble Sort Rounds I', False, 496, 564),
  ('Bubble Sort Rounds II', False, 340, 378),
  ('Nearest Campsites I', False, 216, 253),
  ('Nearest Campsites II', False, 210, 225),
  ('Advertisement', False, 4765, 5042),
  ('Special Substrings', False, 1047, 1149),
  ('Counting LCM Arrays', False, 330, 361),
  ('Square Subsets', False, 257, 283),
  ('Subarray Sum Constraints', False, 505, 539),
  ('Water Containers Moves', False, 207, 219),
  ('Water Containers Queries', False, 241, 253),
  ('Stack Weights', False, 629, 752),
  ('Maximum Average Subarrays', False, 202, 221),
  ('Subsets with Fixed Average', False, 241, 264),
  ('Two Array Average', False, 243, 271),
  ('Pyramid Array', False, 825, 994),
  ('Permutation Subsequence', False, 287, 297),
  ('Bit Inversions', False, 2490, 2807),
  ('Writing Numbers', False, 790, 854),
  ('Letter Pair Move Game', False, 218, 305),
  ('Maximum Building I', False, 2225, 2322),
  ('Sorting Methods', False, 818, 874),
  ('Cyclic Array', False, 1317, 1491),
  ('List of Sums', False, 519, 676)],
 'Additional Problems II': [('Bouncing Ball Steps', False, 278, 307),
  ('Bouncing Ball Cycle', False, 115, 161),
  ('Knight Moves Queries', False, 142, 171),
  ('K Subset Sums I', False, 225, 288),
  ('K Subset Sums II', False, 139, 174),
  ('Increasing Array II', False, 870, 993),
  ('Food Division', False, 556, 665),
  ('Swap Round Sorting', False, 436, 542),
  ('Binary Subsequences', False, 308, 446),
  ('School Excursion', True, 1490, 1575),
  ('Coin Grid', False, 971, 1132),
  ('Grid Coloring II', False, 157, 204),
  ('Programmers and Artists', False, 547, 762),
  ('Removing Digits II', False, 233, 500),
  ('Coin Arrangement', False, 360, 478),
  ('Replace with Difference', False, 149, 179),
  ('Grid Puzzle I', False, 581, 638),
  ('Grid Puzzle II', False, 565, 618),
  ('Bit Substrings', False, 426, 516),
  ('Reversal Sorting', False, 379, 458),
  ('Book Shop II', False, 1366, 1553),
  ('GCD Subsets', False, 466, 480),
  ('Minimum Cost Pairs', False, 161, 205),
  ('Same Sum Subsets', False, 140, 269),
  ('Mex Grid Queries', False, 898, 1050),
  ('Maximum Building II', False, 475, 584),
  ('Stick Divisions', False, 4035, 4712),
  ('Stick Difference', False, 82, 296),
  ('Coding Company', False, 1605, 2096),
  ('Two Stacks Sorting', False, 193, 611)]}

In [67]:
df

,Header,Problem Name,Solved By Me,Solve Count,Attempt Count
0,Introductory Problems,Weird Algorithm,True,170410,178106
1,Introductory Problems,Missing Number,True,147213,153960
2,Introductory Problems,Repetitions,True,127983,132868
3,Introductory Problems,Increasing Array,True,120604,124678
4,Introductory Problems,Permutations,True,105797,108879
...,...,...,...,...,...
395,Additional Problems II,Maximum Building II,False,475,584
396,Additional Problems II,Stick Divisions,False,4035,4712
397,Additional Problems II,Stick Difference,False,82,296
398,Additional Problems II,Coding Company,False,1605,2096
399,Additional Problems II,Two Stacks Sorting,False,193,611

## Analysis

In [75]:
data = df.copy()

In [76]:
print("You have solved: ", data['Solved By Me'].sum(), "/", len(data), ".")
print()
print("Solve Count By Category: \n")
display(data.groupby('Header')['Solved By Me'].sum().sort_values(ascending=False))

You have solved:  160 / 400 .

Solve Count By Category:

Header
Sorting and Searching      35
Graph Algorithms           26
Introductory Problems      23
Dynamic Programming        22
Range Queries              15
Mathematics                12
Sliding Window Problems     9
Tree Algorithms             8
String Algorithms           3
Advanced Graph Problems     2
Advanced Techniques         2
Additional Problems I       1
Additional Problems II      1
Bitwise Operations          1
Geometry                    0
Counting Problems           0
Construction Problems       0
Interactive Problems        0
Name: Solved By Me, dtype: int64

In [78]:
data['Difficulty'] = data['Solve Count'] / data['Attempt Count']

data['Difficulty'] = data['Difficulty'].apply(lambda x: str(round(x*100 *100) / 100) + "%")

In [82]:
print("Should solve next: \n")

unsolved = data.loc[data['Solved By Me'] == False]

unsolved.sort_values(by=['Solve Count', 'Difficulty'], ascending=False).head(10)

Should solve next:

,Header,Problem Name,Solved By Me,Solve Count,Attempt Count,Difficulty
146,Tree Algorithms,Tree Distances I,False,22181,23757,93.37%
147,Tree Algorithms,Tree Distances II,False,18088,18898,95.71%
169,Mathematics,Binomial Coefficients,False,11797,13035,90.5%
23,Introductory Problems,Grid Path Description,False,11209,14395,77.87%
151,Tree Algorithms,Counting Paths,False,10804,11411,94.68%
155,Tree Algorithms,Distinct Colors,False,9926,10872,91.3%
217,Geometry,Point Location Test,False,8294,9213,90.02%
102,Graph Algorithms,Planets Cycles,False,8083,8957,90.24%
156,Tree Algorithms,Finding a Centroid,False,8048,8372,96.13%
179,Mathematics,Fibonacci Numbers,False,7786,9698,80.28%

## Output to JSON

In [ ]:
df.to_json('data/output.json')